# Generated by Django 4.1.2 on 2023-01-05 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0003_carmake_remove_product_and_policy_master_foir_info_and_more"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("phoneNumber", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("pincode", models.IntegerField()),
                ("gender", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                ("insuranceType", models.CharField(max_length=15)),
                ("remark", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MedicalInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sumAssured", models.IntegerField()),
                ("noOfFamilyMembers", models.IntegerField()),
                (
                    "insuranceApplication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.insuranceapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="leads",
            name="completion_status",
            field=models.IntegerField(
                choices=[
                    (0, "Applicant_fill"),
                    (1, "Salaried_fill"),
                    (2, "Documents_fill"),
                ],
                default=None,
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="eligible",
            field=models.IntegerField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="salcompanydetails",
            name="other_company_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="salexistingcreditcard",
            name="other_bank_name",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="salexistingloandetails",
            name="other_bank_name",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="salpersonaldetails",
            name="tenure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="master.tenure",
            ),
        ),
        migrations.CreateModel(
            name="VehicleInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicleType", models.CharField(max_length=20)),
                ("vehicleRegistrationNumber", models.CharField(max_length=15)),
                ("rcBook", models.FileField(upload_to="")),
                ("insuranceCopy", models.FileField(upload_to="")),
                (
                    "insuranceApplication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.insuranceapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tobacco", models.BooleanField()),
                ("annualIncome", models.IntegerField()),
                ("mode", models.CharField(max_length=20)),
                ("sumAssured", models.IntegerField()),
                ("premiumPaymentTerm", models.IntegerField()),
                ("premiumTerm", models.IntegerField()),
                (
                    "insuranceApplication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.insuranceapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalInsuranceFamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("phoneNumber", models.CharField(max_length=13)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("pincode", models.IntegerField()),
                ("gender", models.CharField(max_length=15)),
                ("age", models.IntegerField()),
                ("typeOfRelationship", models.CharField(max_length=50)),
                ("diseaseSuffered", models.BooleanField()),
                (
                    "diseaseName",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "medicalInsurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.medicalinsurance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("builder_name", models.CharField(max_length=50)),
                ("proj_name", models.CharField(max_length=50)),
                ("apf_num", models.CharField(max_length=50)),
                ("market_val", models.IntegerField()),
                ("distress_val", models.IntegerField()),
                ("prop_loc", models.CharField(max_length=50)),
                (
                    "oc_available",
                    models.BooleanField(
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ]
                    ),
                ),
                (
                    "cc_available",
                    models.BooleanField(
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ]
                    ),
                ),
                (
                    "municipal_approved",
                    models.BooleanField(
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ]
                    ),
                ),
                ("area_size", models.IntegerField()),
                (
                    "property_used_for",
                    models.BooleanField(
                        choices=[
                            (None, "Select Rental Or NonRental"),
                            (True, "Rental"),
                            (False, "NonRental"),
                        ]
                    ),
                ),
                ("rent", models.IntegerField()),
                (
                    "property_tax_paid",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "society_formed",
                    models.BooleanField(
                        blank=True,
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ],
                        null=True,
                    ),
                ),
                ("building_age", models.IntegerField()),
                (
                    "structural_report",
                    models.BooleanField(
                        choices=[
                            (None, "Select Yes Or No"),
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("Not aware", "Not aware"),
                        ]
                    ),
                ),
                (
                    "car_parking",
                    models.BooleanField(
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ]
                    ),
                ),
                ("car_parking_amt", models.IntegerField(blank=True, null=True)),
                (
                    "agreement_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.agreementtype",
                    ),
                ),
                ("apf_approved_lender", models.ManyToManyField(to="master.bankname")),
                (
                    "area_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.areain"
                    ),
                ),
                (
                    "area_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.areatype",
                    ),
                ),
                (
                    "prop_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.city"
                    ),
                ),
                (
                    "prop_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.propertyin",
                    ),
                ),
                (
                    "prop_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.state"
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.roomtype",
                    ),
                ),
                (
                    "seller_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.status"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarRefinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manu_year", models.CharField(max_length=10)),
                (
                    "mortage",
                    models.BooleanField(
                        choices=[
                            (None, "Select Yes Or No"),
                            (True, "Yes"),
                            (False, "No"),
                        ]
                    ),
                ),
                (
                    "roi",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "loanamounttaken",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "loanamountso",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("insurance", models.CharField(max_length=50)),
                ("validtill", models.CharField(max_length=50)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.bankname",
                    ),
                ),
                (
                    "carmake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.carmake"
                    ),
                ),
                (
                    "sub_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.submodel",
                    ),
                ),
                (
                    "tenure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.tenure",
                    ),
                ),
            ],
        ),
    ]
