# Generated by Django 4.1.2 on 2023-01-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_insuranceapplication_medicalinsurance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leads",
            name="eligible",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")], default=False
            ),
        ),
    ]
