# Generated by Django 4.1.2 on 2022-12-21 14:50

from django.db import migrations , models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        
    ]
