# Generated by Django 4.0.3 on 2023-01-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foir_info',
            name='foir_data',
        ),
        migrations.RemoveField(
            model_name='multiplier_info',
            name='multiplier_data',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='foir_info',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='multiplier_info',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='rate_of_interest',
        ),
        migrations.AddField(
            model_name='foir_data',
            name='foir_info_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='master.foir_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foir_info',
            name='pp_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.product_and_policy_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplier_data',
            name='mult_info_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='master.multiplier_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='multiplier_info',
            name='pp_id',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='master.product_and_policy_master'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateofinterest_info',
            name='pp_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='master.product_and_policy_master'),
            preserve_default=False,
        ),
    ]
