# Generated by Django 4.1.2 on 2022-12-31 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalRate_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.BigIntegerField(null=True)),
                ("max_salary", models.BigIntegerField(null=True)),
                ("loan_min_amount", models.BigIntegerField()),
                ("loan_max_amount", models.BigIntegerField()),
                ("rate_of_interest", models.BigIntegerField()),
                ("processing_fee", models.BigIntegerField(null=True)),
            ],
        ),
        
        migrations.CreateModel(
            name="RateOfInterest_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cocat_type", models.CharField(max_length=250, null=True)),
                (
                    "additional_rate_info",
                    models.ManyToManyField(to="master.additionalrate_info"),
                ),
                (
                    "pp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.product_and_policy_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerTenure_Multiplier_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("multiplier", models.IntegerField()),
                (
                    "associated_tenure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.tenure"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerTenure_Foir_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foir", models.IntegerField()),
                (
                    "associated_tenure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.tenure"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multiplier_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cocat_type", models.CharField(max_length=250)),
                (
                    "pp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.product_and_policy_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multiplier_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.BigIntegerField()),
                ("max_salary", models.BigIntegerField()),
                (
                    "mult_info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.multiplier_info",
                    ),
                ),
                (
                    "tenure_multipliers",
                    models.ManyToManyField(to="master.pertenure_multiplier_data"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Foir_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cocat_type", models.CharField(max_length=250)),
                (
                    "pp_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.product_and_policy_master",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Foir_Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_salary", models.BigIntegerField()),
                ("max_salary", models.BigIntegerField()),
                (
                    "foir_info_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.foir_info",
                    ),
                ),
                (
                    "tenure_foirs",
                    models.ManyToManyField(to="master.pertenure_foir_data"),
                ),
            ],
        ),
    ]
