# Generated by Django 4.1.2 on 2023-01-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_additionalrate_info_product_and_policy_master_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carmake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carmake", models.CharField(max_length=25)),
                ("effective_date", models.DateField(null=True)),
                ("ineffective_date", models.DateField(blank=True, null=True)),
            ],
        ),
   
        migrations.CreateModel(
            name="Submodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_model", models.CharField(max_length=50)),
                ("effective_date", models.DateField(null=True)),
                ("ineffective_date", models.DateField(blank=True, null=True)),
                (
                    "carmake",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="master.carmake"
                    ),
                ),
            ],
        ),
    ]
