# Generated by Django 4.0.3 on 2022-12-22 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_delete_deductiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalRate_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.BigIntegerField(null=True)),
                ('max_salary', models.BigIntegerField(null=True)),
                ('loan_min_amount', models.BigIntegerField()),
                ('loan_max_amount', models.BigIntegerField()),
                ('rate_of_interest', models.BigIntegerField()),
                ('processing_fee', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foir_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.BigIntegerField()),
                ('max_salary', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiplier_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.BigIntegerField()),
                ('max_salary', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='foir_bt',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='foir_fresh',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='multiplier_bt',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='multiplier_fresh',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='processing_fee',
        ),
        migrations.RemoveField(
            model_name='product_and_policy_master',
            name='tenure',
        ),
        migrations.AddField(
            model_name='companycatergorytypes',
            name='banks',
            field=models.ManyToManyField(to='master.bankname'),
        ),
        migrations.CreateModel(
            name='RateOfInterest_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocat_type', models.CharField(max_length=250, null=True)),
                ('additional_rate_info', models.ManyToManyField(to='master.additionalrate_info')),
            ],
        ),
        migrations.CreateModel(
            name='PerTenure_Multiplier_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.IntegerField()),
                ('associated_tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.tenure')),
            ],
        ),
        migrations.CreateModel(
            name='PerTenure_Foir_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foir', models.IntegerField()),
                ('associated_tenure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.tenure')),
            ],
        ),
        migrations.CreateModel(
            name='Multiplier_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocat_type', models.CharField(max_length=250)),
                ('multiplier_data', models.ManyToManyField(to='master.multiplier_data')),
            ],
        ),
        migrations.AddField(
            model_name='multiplier_data',
            name='tenure_multipliers',
            field=models.ManyToManyField(to='master.pertenure_multiplier_data'),
        ),
        migrations.CreateModel(
            name='Foir_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocat_type', models.CharField(max_length=250)),
                ('foir_data', models.ManyToManyField(to='master.foir_data')),
            ],
        ),
        migrations.AddField(
            model_name='foir_data',
            name='tenure_foirs',
            field=models.ManyToManyField(to='master.pertenure_foir_data'),
        ),
        migrations.AddField(
            model_name='product_and_policy_master',
            name='foir_info',
            field=models.ManyToManyField(to='master.foir_info'),
        ),
        migrations.AddField(
            model_name='product_and_policy_master',
            name='multiplier_info',
            field=models.ManyToManyField(to='master.multiplier_info'),
        ),
        migrations.AddField(
            model_name='product_and_policy_master',
            name='rate_of_interest',
            field=models.ManyToManyField(to='master.rateofinterest_info'),
        ),
    ]
